{"name": "Ошибка при непрравильно указанном поле login", "status": "passed", "steps": [{"name": "Авторизация курьера", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'неверный логин/пароль', 'password': 'uvyxepwfvoegjxhsbckavdvumwvmdplbhyxugquumxrjyzuwplvcjaslsufvlvkbuzygipovbqydnwmwcheqnvqgmkulzhlewcmk'}"}], "start": 1734302229522, "stop": 1734302229666}], "parameters": [{"name": "invalid_data_fields", "value": "'login'"}], "start": 1734302229522, "stop": 1734302229667, "uuid": "c1852896-4074-486b-af26-14f148af4eca", "historyId": "4c9cd0a9df13bba22c27258be7816db3", "testCaseId": "5e7a8ed2e7ddfa7c8c95b1ddf06c09cf", "fullName": "tests.test_login_courier.TestLoginCourier#test_invalid_data_login_courier_error_not_found", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "i113855765"}, {"name": "thread", "value": "38750-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}